name: ci

on:
  pull_request:
  push:
    branches:
      # - 'master'
      - 'development'
jobs:
  docker_alpine:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to DockerHub
        uses: docker/login-action@v1 
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - 
        run: npm ci
      - run: npm install -g gulp
      - run: gulp
      - 
        name: Build and push (alpine)
        id: docker_build_alpine
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          file: alpine.Dockerfile
          tags: octofarm/octofarm:dev-alpine
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
