name: Node.js CI

on:
  push:
    branches: [ develop, master ]
  pull_request:
jobs:
  nodejs-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile
        working-directory: "server_2x"
      - run: npm run build --if-present
        working-directory: "server_2x"
      - run: npm run e2e
        name: "Run end-to-end tests"
        working-directory: "server_2x"